stages:
- name: Integration--initial pipeline
  iiidevops: initial-pipeline
  steps:
  - envFrom:
    - sourceKey: api-origin
      sourceName: nexus
      targetKey: api_origin
    runScriptConfig:
      image: iiiorg/iiidevops-cli:0.0.4
      shellScript: curl --location -s --request POST ${api_origin}/rancher/delete_app
        --form project_name=${CICD_GIT_REPO_NAME} --form branch_name=${CICD_GIT_BRANCH}
        && curl --location -s --request POST ${api_origin}/project/issues_commit_by_name
        --form project_name=${CICD_GIT_REPO_NAME} && count-src.pl
- name: Deploy--DB
  iiidevops: deployed-environments
  steps:
  - applyAppConfig:
      answers:
        db.gui: true
        db.name: todo_db
        db.password: DevOps_123
        db.tag: 10.5
        db.type: mariadb
        db.username: iiidevops
        git.branch: ${CICD_GIT_BRANCH}
        git.commitID: ${CICD_GIT_COMMIT}
        git.repoName: ${CICD_GIT_REPO_NAME}
        git.url: ${CICD_GIT_URL}
        harbor.host: harbor-dev3.iiidevops.org
        volumeMounts.nfs.enabled: false
        volumeMounts.nfs.server: 10.20.0.100
        volumeMounts.project : ${CICD_GIT_REPO_NAME}
        volumeMounts.uuid : fd09f2da-b212-11ec-9a09-5ed3230a7360
      catalogTemplate: cattle-global-data:iii-dev-charts3-db
      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-db
      targetNamespace: ${CICD_GIT_REPO_NAME}
      version: 0.3.5
  when:
    branch:
      include:
      - skip-master
- name: Deploy--Wait DB deployment
  iiidevops: deployed-environments
  steps:
  - env:
      deploy_name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-db
      max_wait: 128
      namespace: ${CICD_GIT_REPO_NAME}
    envFrom:
    - sourceKey: API_TOKEN
      sourceName: pipeline-api-key
      targetKey: rancher_api_token
    - sourceKey: rancher-url
      sourceName: rancher
      targetKey: rancher_url
    runScriptConfig:
      image: iiiorg/iiidevops-cli:0.0.4
      shellScript: rancher login ${rancher_url} -t ${rancher_api_token} --skip-verify; 
        deploy-wait.pl
  when:
    branch:
      include:
      - skip-master
